---
# Example deployment manifest for Pure BPM blacksmith
# BPM manages all processes directly - no monit required
# 
# Process management commands:
#   bpm list                           # List all processes
#   bpm start blacksmith -p <process>  # Start specific process  
#   bpm stop blacksmith -p <process>   # Stop specific process
#   bpm logs blacksmith -p <process>   # View process logs

name: blacksmith

releases:
- name: blacksmith
  version: latest
- name: bpm
  version: "1.4.20"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.20"
  sha1: sha256:1984129b352cd414e29a7dcffcf076049a776afa511cd44b587065f6e618cc6d

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: blacksmith
  instances: 1
  azs: [z1]
  networks: [{name: blacksmith}]
  stemcell: default
  vm_type: blacksmith
  persistent_disk: 8192

  jobs:
  # BPM job is required for process management
  - name: bpm
    release: bpm

  - name: blacksmith
    release: blacksmith
    properties:
      # Standard blacksmith properties
      debug: false
      env: production

      broker:
        port: 3000
        username: blacksmith
        password: ((blacksmith-password))

      bosh:
        username: admin
        password: ((bosh-password))
        address: https://((bosh-address)):25555
        skip_ssl_validation: true
        ca_cert: ((bosh-ca-cert))

      # Example: Override resource limits (optional)
      # These would require custom operations files or variables
      # to modify the bpm.yml template

variables:
- name: blacksmith-password
  type: password
- name: bosh-password  
  type: password
- name: bosh-ca-cert
  type: certificate

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000