---
name: blacksmith

instance_groups:
  - name: blacksmith
    instances: 1
    stemcell:  default
    azs:       [z1]
    vm_type:   default
    persistent_disk: 2_048
    networks:
      - name:       default
        static_ips: [((blacksmith_ip))]
    jobs:
      - release: blacksmith
        name:    blacksmith
        properties:
          debug: false
          env:   ((blacksmith_ip))

          broker:
            username: blacksmith
            password: ((broker_password))

          bosh:
            username: ((bosh_username))
            password: ((bosh_password))
            address:  https://((bosh_ip)):25555

variables:
  - name: broker_password
    type: password

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  max_in_flight: 1
  max_errors: 1

stemcells:
  - alias:   default
    os:      ubuntu-bionic
    version: latest

releases:
- name:    blacksmith
  version: 1.5.0
  url:     https://github.com/blacksmith-community/blacksmith-boshrelease/releases/download/v1.5.0/blacksmith-1.5.0.tgz
  sha1:    65a12c44cad9766b798f2e7f3990127b90f39d59
